### ISSUE TITLE
Git rebase

### ISSUE THREAD

**Issue by professor** [kejadlen/git-together#16]
Hi,

I just played with git-together and tried git-together rebase -i, it looks like it maintains the existing author and committer. 

For my current team, that behavior is really nice. I thought that maybe the committer would be reset by the current settings of git-together.

Were you planning on changing it?

**Comment by kejadlen** [comment]
I actually don't have a great grasp of what the rebase behavior currently is, since it's something that fell out of the implementation, rather than through purposeful design. 😅

I assume that git-together doesn't change the author/committer for rebases, but I'm not sure whether that's something that is desired or not? IIRC, git-duet gets around this via an alias (or script) that fixes the author/committer post-hoc, but I'm a little wary of the level of complexity and reason-ability of such a solution.

**Comment by professor** [comment]
So far we are liking what git-together does with rebasing. Maybe we update the readme to remove rebase as a "todo"

**Comment by kejadlen** [comment]
Excellent, done.
