### ISSUE TITLE
Exit code from git is not forwarded

### ISSUE THREAD

**Issue by jonsmithers** [kejadlen/git-together#42]
`git diff --quiet` should return an exit code of 1 when a difference exists. When it's aliased to `git-together`, it always returns an exit code of 0.

**Comment by rhoughton-pivot** [comment]
Also occurs for `git merge-base --is-ancestor HEAD HEAD^`, which should return 1 always.

**Comment by kejadlen** [comment]
This is fixed in #40, but a comedy of errors has resulted in a release not being cut. My foolish decision to use nightly for development and builds has bitten me in the ass due to slice patterns being only [partially stabilized](https://github.com/rust-lang/rust/issues/62254).

I'll look at fixing this and cutting another release this weekend, but if anyone else wants to take a crack at it, I don't think it should be too difficult.

**Comment by rhoughton-pivot** [comment]
@kejadlen I appreciate it. I pounded my fists on fixing the slice patterns using the latest stable of rustc, but that isn't my language of choice and I got stuck pretty quickly 😞 I badly want this to work though, so I will likely circle back to it.

**Comment by kejadlen** [comment]
Cut a new release (thanks, @ipsi!), can someone check if [v0.1.0-alpha.21](https://github.com/kejadlen/git-together/releases/tag/v0.1.0-alpha.21) works?

And if it does, if you want to update [the tap](https://github.com/pivotal-legacy/homebrew-tap/blob/master/git-together.rb), I’d appreciate it.
